services:
  app:
    build: .
    image: rhossain16/text-processor-api:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - ENV_FILE=.env.${NODE_ENV}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: