name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI}}
      MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Set up .env file for e2e
        run: |
          echo "NODE_ENV=prod" > .env.prod
          echo "MONGO_URI=${{ env.MONGO_URI_TEST }}" >> .env.prod
          echo "MONGO_URI_TEST=${{ env.MONGO_URI_TEST }}" >> .env.prod

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run E2E tests
        run: npm run test:e2e
